<a href="https://colab.research.google.com/github/Navyareddy1124/Python_Frameworks/blob/main/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Import NumPy using an alias
import numpy as np

In [ ]:
#Check version and configuration
print(np.__version__)      # Shows version
np.show_config()           # Shows build configuration


2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.2/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.27  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Zen MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.27
Compilers:
  c:
    commands: cc
    linker: ld.bfd
    name

In [ ]:
#Create a vector filled with zeros of size 10
Z=np.zeros(10,dtype=int)
print(Z)

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
#Create a zero vector of size 10 with the fifth element as 1
a = np.zeros(10,dtype=int)
a[4]=1
print(a)

[0 0 0 0 1 0 0 0 0 0]


In [ ]:
#Create a vector with values from 10 to 49
vec= np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#Reverse a vector
rev=vec[::-1]
print(rev)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
#Create a 3x3 matrix with values from 0 to 8
mat=np.arange(0,9).reshape(3,3)
print(mat)



[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Find indices of non-zero elements
a = np.array([1, 0, 2, 0, 3, 0,0,4,5,0])
indices = np.nonzero(a)
print(indices)

(array([0, 2, 4, 7, 8]),)


In [ ]:
#Create a 3x3 identity matrix
iden=np.eye(3)
print(iden)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Generate a 3x3x3 array with random values
arr = np.random.rand(3, 3, 3)
print(arr)

[[[0.46001588 0.27048737 0.46370194]
  [0.52836895 0.3029328  0.24138979]
  [0.79227991 0.61769578 0.20024558]]

 [[0.34195907 0.91985022 0.04915962]
  [0.69499747 0.962028   0.94396048]
  [0.41923776 0.37287416 0.22987295]]

 [[0.96937643 0.59475366 0.4529393 ]
  [0.96228935 0.79543066 0.74949903]
  [0.91969023 0.24999204 0.22050378]]]


In [ ]:
#Find min and max in a 10x10 random matrix
m = np.random.random((10, 10))
print(m)

m_min, m_max = m.min(), m.max()
print(f"minum and maximum from (10,10) matrix is {m_min}, {m_max}")

[[0.13833806 0.88477922 0.53134879 0.68013207 0.84222964 0.71088866
  0.38694456 0.43719607 0.16472524 0.93220586]
 [0.28669608 0.73585665 0.22640144 0.76143889 0.94819556 0.22027564
  0.22941832 0.90627886 0.96684734 0.40301587]
 [0.14085162 0.23335496 0.30209395 0.8323999  0.56131367 0.79194054
  0.77515446 0.12071854 0.13839997 0.20443502]
 [0.71281496 0.9051154  0.79320557 0.90647251 0.65428016 0.50985421
  0.50123702 0.67739017 0.68131806 0.47672751]
 [0.98226208 0.39002087 0.86949191 0.47729557 0.32940657 0.59321882
  0.80498812 0.20508725 0.51605697 0.37214637]
 [0.84317447 0.72179372 0.74974483 0.84331682 0.23396532 0.24059689
  0.37922249 0.83569655 0.65523099 0.88521798]
 [0.17595897 0.66781964 0.47111598 0.20367444 0.42605587 0.5926622
  0.89123994 0.02719415 0.93275746 0.83523827]
 [0.24427911 0.26170384 0.87827664 0.70146012 0.67232929 0.48990753
  0.05837152 0.60637248 0.4000699  0.53831666]
 [0.57625869 0.86030094 0.01398359 0.15983682 0.24359966 0.6810317
  0.06705858 0

In [ ]:
#Calculate mean of a random vector of size 30
v = np.random.rand(30)
print(v)
mean = v.mean()
print(f"mean of vector of size 30 is {mean}")

[0.86864968 0.92425832 0.35478071 0.67013572 0.68586406 0.11444154
 0.40442127 0.91526564 0.86389839 0.75798471 0.97835113 0.60063938
 0.51894991 0.822339   0.90123962 0.74985335 0.16588748 0.59738271
 0.08109555 0.60760729 0.13480401 0.36519342 0.90525112 0.68994704
 0.50084322 0.73245275 0.06102729 0.5381004  0.88159969 0.37198592]
mean of vector of size 30 is 0.5921416776336801


In [ ]:
#Create a 2D array with 1s on border and 0s inside
import numpy as np
a = np.ones((5, 5))
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#Results of NaN operations

import numpy as np
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))


nan
False
False
nan
True


In [ ]:
#Create matrix with values below the diagonal
m = np.tril(np.ones((4, 4)))
print(m)

[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]


In [ ]:
#Create an 8x8 checkerboard pattern
a = np.zeros((8, 8))
a[1::2, ::2] = 1
a[::2, 1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
#Create checkerboard pattern using tile
pattern = np.array([[0, 1], [1, 0]])
print(pattern)
checker = np.tile(pattern, (4, 4))   # used to repeat an array a specified number of times
print(checker)

[[0 1]
 [1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#Matrix multiplication
A = np.ones((2, 3),dtype=int)
B = np.ones((3, 2),dtype=int)
C = np.dot(A, B)
print(C)


[[3 3]
 [3 3]]


In [ ]:
#Output of sum(range(5), -1) vs np.sum(range(5), -1)
print(sum(range(5), -1))
print(np.sum(range(5), -1))


9
10


In [ ]:
#Legal vs Illegal operations
#Legal:
np.array([1, 2, 3]) + np.array([4, 5, 6])   # the shape matches
np.array([1, 2, 3]) * 2

array([2, 4, 6])

In [ ]:
#Illegal
np.array([1, 2, 3]) + np.array([1, 2])



ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [ ]:
#Division by zero
div_zero=np.array([1, 0]) / np.array([0, 0])
print(div_zero)

[inf nan]


/tmp/ipython-input-3818268295.py:2: RuntimeWarning: divide by zero encountered in divide
  div_zero=np.array([1, 0]) / np.array([0, 0])
/tmp/ipython-input-3818268295.py:2: RuntimeWarning: invalid value encountered in divide
  div_zero=np.array([1, 0]) / np.array([0, 0])


In [ ]:
#Round a float array away from zero
a = np.array([-1.2, 1.2, -2.8, 2.8])
rounded = np.copysign(np.ceil(np.abs(a)), a)
print(rounded)

[-2.  2. -3.  3.]


In [ ]:
#Extract integer part of a float
a = np.random.uniform(0, 10, 5)
print(a)
np.floor(a)
np.ceil(a)
np.trunc(a)
a.astype(int)

[4.65436728 9.05605491 8.02799912 4.8865544  6.30049915]


array([4, 9, 8, 4, 6])

In [ ]:
#Create 5x5 matrix with row values 0–4
sqr_matrix=np.tile(np.arange(5),(5,1))
print(sqr_matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
#Create evenly spaced values between 0 and 1
print(np.linspace(0,1,11,endpoint=False))

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
#Sort a random array
Arr=np.random.rand(10)
print(Arr)
sorted_arr= Arr.sort()
print(sorted_arr)

[0.89397611 0.86273621 0.59229026 0.98148919 0.88816839 0.75927388
 0.7617422  0.69406615 0.51547311 0.79738663]
None


In [ ]:
#Check if two arrays are equal
myarr1=np.array_equal(np.array([1, 2]), np.array([1, 2]))
myarr2=np.array_equal(np.array([1, 2]), np.array([3, 5]))
print(myarr1)
print(myarr2)

True
False


**Intermediate**

In [ ]:
#Convert Cartesian coordinates to polar coordinates
x = np.array([1, 2])
y = np.array([2, 2])
r = np.sqrt(x**2 + y**2)
theta = np.arctan2(y, x)
print(theta)

[1.10714872 0.78539816]


In [ ]:
#Replace the maximum value in an array with zero
A = np.array([1,23,15,7,19])
A[A == A.max()] = 0
print(A)

[ 1  0 15  7 19]


In [ ]:
#Create a structured array for (x, y) coordinate pairs
coords = np.zeros(5, dtype=[('x', float), ('y', float)])
coords['x'] = np.arange(5)
coords['y'] = np.arange(5) * 2
print(coords)

[(0., 0.) (1., 2.) (2., 4.) (3., 6.) (4., 8.)]


In [ ]:
#Find the closest value to a given scalar in an array
a = np.array([1, 3, 7, 9, 11])
target = 8
closest = a[np.abs(a - target).argmin()]
print(closest)

7


In [ ]:
#Cast a float array to integer type in place
a = np.array([1.7, 2.9, 3.1])
a[:] = a.astype(int)
print(a)

[1. 2. 3.]


In [ ]:
#Iterate through all elements in a NumPy array with indices
a = np.array([[1, 2], [3, 4]])
for index, value in np.ndenumerate(a):
    print(index, value)



(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [ ]:
#Randomly place a specific number of elements in a 2D array
a = np.zeros((5, 5))
n = 5
indices = np.random.choice(a.size, n, replace=False)
a.ravel()[indices] = 1
print(a)


[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#Subtract the row mean from a matrix
a = np.array([[1, 2], [3, 4]])
row_means = np.mean(a, axis=1, keepdims=True)
a_subtracted = a - row_means
print(a_subtracted)

[[-0.5  0.5]
 [-0.5  0.5]]


In [ ]:
#Sort a 2D array based on the values of one column
a = np.array([[3, 7], [1, 9], [2, 5]])
a_sorted = a[a[:, 1].argsort()]
print(a_sorted)


[[2 5]
 [3 7]
 [1 9]]


In [ ]:
#Check if a 2D array contains any null (zero-only) columns
a = np.array([[0, 1, 0],
              [0, 0, 0],
              [0, 2, 0]])
null_cols = np.all(a == 0, axis=0)
print(null_cols)

[ True False  True]


In [ ]:
#Find the nearest value to a given number in a NumPy array
a = np.array([2.5, 8.1, 4.3, 6.7])
target = 5
nearest = a[np.abs(a - target).argmin()]
print(nearest)

4.3


In [ ]:
#Increment elements in an array using an index array with repeats
a = np.zeros(5, int)
indices = np.array([1, 1, 2, 3])
np.add.at(a, indices, 1)
print(a)

[0 2 1 1 0]


In [ ]:
#Accumulate values into an array based on indices
values = np.array([10, 20, 30])
indices = np.array([0, 1, 0])
result = np.bincount(indices, weights=values)
print(result)

[40. 20.]


In [ ]:
#Count unique colors in a 3D image array
image = np.random.randint(0, 256, (4, 4, 3), dtype=np.uint8)
colors = np.unique(image.reshape(-1, 3), axis=0)
num_colors = len(colors)
print(num_colors)

16


In [ ]:
#Compute the sum across the last two axes of a 4D array
a = np.random.rand(2, 3, 4, 5)
Results = a.sum(axis=(-2, -1))
print(Results)

[[ 9.71086228  9.88928556 10.98590264]
 [10.42165197  9.54977765  8.99225211]]


In [ ]:
#Calculate means of grouped values in an array
values = np.array([1, 2, 3, 4, 5, 6])
groups = np.array([1, 1, 2, 2, 3, 3])
means = [values[groups == g].mean() for g in np.unique(groups)]
print(means)


[np.float64(1.5), np.float64(3.5), np.float64(5.5)]


In [ ]:
#Efficiently get the diagonal of a matrix dot product
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
diag = np.einsum('ij,ji->i', A, B)
print(diag)

[0.97906186 1.16517814 0.80422246]


In [ ]:
#Swap two rows in a matrix (in-place)
M = np.arange(12).reshape(4,3)
i, j = 0, 2
M[[i, j]] = M[[j, i]]
print(M)


[[ 6  7  8]
 [ 3  4  5]
 [ 0  1  2]
 [ 9 10 11]]


In [ ]:
#Recreate original values from a bincount
bc = np.bincount([0,2,2,5,0])
arr = np.repeat(np.arange(len(bc)), bc)
print(arr)

[0 0 2 2 5]


In [ ]:
#Raise array to the power 3 (three ways)
a = np.arange(5, dtype=float)
r1 = a ** 3
r2 = a * a * a
r3 = np.power(a, 3)
print(r1)
print(r2)
print(r3)

[ 0.  1.  8. 27. 64.]
[ 0.  1.  8. 27. 64.]
[ 0.  1.  8. 27. 64.]


In [ ]:
#inner, outer, sum, multiplication using einsum
a = np.array([1,2,3])
b = np.array([4,5,6])
inner = np.einsum('i,i->', a, b)
outer = np.einsum('i,j->ij', a, b)
total_sum = np.einsum('ij->', A)
elemwise = np.einsum('ij,ij->ij', A, B)
print(inner)
print(outer)
print(total_sum)
print(elemwise)

32
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
5.641423046912164
[[0.64073488 0.49837262 0.05201349]
 [0.21198538 0.2066243  0.41213408]
 [0.21170932 0.42051445 0.25538069]]


In [ ]:
#Vertically and horizontally stack two arrays
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
v_stack=np.vstack((a, b))
h_stack=np.hstack((a, b.T))
print(v_stack)
print(h_stack)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [ ]:
#Apply a custom function to each element
fun=np.array([1,2,3,4,5])
sqr_fun=np.square(fun)
print(sqr_fun)

[ 1  4  9 16 25]


In [ ]:
#Remove duplicate rows in a 2D array
arr1 = np.array([[1,2], [3,4], [1,2]])
uniq_row=np.unique(arr1, axis=0)
print(uniq_row)

[[1 2]
 [3 4]]


In [ ]:
#Correlation coefficient between two vectors
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
corr = np.corrcoef(x, y)
print(corr)


[[1. 1.]
 [1. 1.]]


In [ ]:
#Perform one-hot encoding
a = np.array([0, 1, 2])
one_hot = np.eye(a.max()+1)[a]
print(one_hot)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Find shape and number of elements
np_arr = np.array([[1,2,3],[4,5,6]])
print(np_arr.shape)
print(np_arr.size)


(2, 3)
6


In [ ]:
#Reshape array without changing data
a_arr= np.arange(6)
reshaped = a_arr.reshape(2, 3)
print(reshaped)


[[0 1 2]
 [3 4 5]]


In [ ]:
#Flatten a multi-dimensional array
abc = np.array([[1,2],[3,4]])
print(abc.flatten())
print(abc.ravel())


[1 2 3 4]
[1 2 3 4]


In [ ]:
#Get cumulative sum along an axis
val= np.array([[1,2,3],
              [4,5,6]])
print(np.cumsum(val, axis=1))



[[ 1  3  6]
 [ 4  9 15]]


In [ ]:
#Element-wise maximum/minimum of two arrays
arr1 = np.array([11, 42, 29])
arr2 = np.array([31, 12, 53])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))


[31 42 53]
[11 12 29]


In [ ]:
#Broadcasting arrays with different shapes
my_arr1 = np.array([[1],[2],[3]])
my_arr2 = np.array([10,20,30])
print(my_arr1+my_arr2)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [ ]:
  #Transpose a matrix and perform dot products
a = np.array([[1,2],[3,4]])
print(a.T)
res=np.dot(a, a.T)
print(res)

[[1 3]
 [2 4]]
[[ 5 11]
 [11 25]]


In [ ]:
#Check for NaN or infinite values
a = np.array([1, 0,np.nan,10,np.inf])
print(np.isnan(a))
print(np.isinf(a))


[False False  True False False]
[False False False False  True]


In [ ]:
#Extract diagonal, upper, and lower triangles
a = np.arange(9).reshape(3,3)
print(np.diag(a))
print(np.triu(a))
print(np.tril(a))

[0 4 8]
[[0 1 2]
 [0 4 5]
 [0 0 8]]
[[0 0 0]
 [3 4 0]
 [6 7 8]]
